"""auto generate post to add image column

Revision ID: 2db5634200ce
Revises: a7cb41712a1e
Create Date: 2022-06-16 10:14:40.939582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db5634200ce'
down_revision = 'a7cb41712a1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'posts', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###
